---
abstract: 'rewrite HTML links to be relative to a given URL'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Carp: '0'
  Exporter: '5'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Rebase
no_index:
  directory:
    - t
    - inc
requires:
  Text::Unidecode: '0'
  perl: '5.006'
resources:
  repository: http://github.com/Corion/html-rebase
version: '0.01'
